/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YS6prOEJWLF
 */

import React from 'react'
import Link from 'next/link';
import { Button } from "../components/ui/button"

export default function v0() {
  return (
    <div className="flex flex-col min-h-screen text-gray-300 bg-gradient-to-b from-upperColor to-lightUniverse">
      <nav className="bg-slate-800 p-4">
        <header className="mx-auto flex items-center justify-between">
        <a href="https://ft-lancho.vercel.app/">
            <div>
              <h1 className="text-xl font-semibold">ft_lanches | Nutrindo mentes</h1>
            </div>
          </a>
          <div className="flex space-x-4">
            <Link href="https://benfeitoria.com/projeto/ftlanches" target='_blank'>
              <Button className="text-2xl bg-pink-600 text-gray-300 hover:bg-pink-950" type="button">
                doar
              </Button>
            </Link>
            <Button className="text-2xl bg-blue-800 text-gray-300 hover:bg-blue-950" type="button">
              login
            </Button>
          </div>
        </header>
      </nav>
      <main className="flex-grow mx-auto max-w-6xl flex-col justify-center bg-gradient-to-b from-black to-darkUniverse">
        <img
          alt="ft_lanches"
          className="w-full"
          height={400}
          src="/ft_lanches.jpg"
          style={{
            aspectRatio: "800/400",
            objectFit: "cover",
          }}
          width={800}
        />
        <div className="relative">
          {/* <img
            alt="background"
            className="w-full h-full"
            height={400}
            src="/stars.jpg"
            style={{
              aspectRatio: "1000/400",
              objectFit: "cover",
            }}
            width={800}
          /> */}
          <div className="p-4 h-full flex flex-col justify-center items-center text-center text-cyan-50 space-y-4 bg-black bg-opacity-50">
            <p className="lg:text-5xl md:text-4xl sm:text-2xl">
              Estudamos em uma escola de engenharia de software totalmente gratuita e presencial,
              cujo objetivo é diversificar o cenário da tecnologia.
            </p>
            <p className="lg:text-4xl md:text-3xl sm:text-base">
              Recentemente, um grupo de alunos consultou a comunidade e percebeu que alguns colegas,
              apesar de receberem bolsas da instituição, ainda enfrentam dificuldades financeiras
              para se alimentar quando estão no campus.
            </p>
            <p className="lg:text-4xl md:text-3xl sm:text-base">
              Isso tem levado muitos deles a não comerem ou a se alimentarem predominantemente com produtos industrializados.
            </p>
            <p className="lg:text-4xl md:text-3xl sm:text-base">
              Tomando uma ação prática para resolver o problema, estes alunos se juntaram para buscar uma solução.
            </p>
            <p className="lg:text-4xl md:text-3xl sm:text-base">
              Fechamos uma parceria com um restaurante perto da escola em que os beneficiados pelo projeto ft_lanches
              poderão fazer refeições e os apoiadores ficarão responsáveis por pagá-las ao final do mês.
            </p>
            <p className="lg:text-5xl md:text-4xl sm:text-3xl">
              Alimente o conhecimento - Apoie nossos Cadetes!
            </p>
            <p className="mb-2 text-center lg:text-5xl md:text-4xl sm:text-3xl">
              São 3 opções de assinatura:
            </p>
            <div className="grid grid-cols-3 gap-4 p-4">
              <Link href="https://benfeitoria.com/projeto/ftlanches" target='_blank'>
                <Button className="mx-auto flex 4xl bg-pink-600 text-gray-300 hover:bg-pink-950" type="button">
                  R$30/mês
                </Button>
              </Link>
              <Link href="https://benfeitoria.com/projeto/ftlanches" target='_blank'>
                <Button className="mx-auto flex 4xl bg-pink-600 text-gray-300 hover:bg-pink-950" type="button">
                R$90/mês
                </Button>
              </Link>
              <Link href="https://benfeitoria.com/projeto/ftlanches" target='_blank'>
                <Button className="mx-auto flex 4xl bg-pink-600 text-gray-300 hover:bg-pink-950" type="button">
                R$150/mês
                </Button>
              </Link>
            </div>
          </div>
        </div>
        <div>
          <img
            alt="ft_lanche"
            className="w-full"
            height={400}
            src="/plate.jpg"
            style={{
              aspectRatio: "450/400",
              objectFit: "cover",
            }}
            width={800}
          />
        </div>
      </main>
      <footer className="bg-gray-800 p-4">
        <div className="container mx-auto text-center">
          <Link href="https://www.42sp.org.br" target='_blank'>
            <Button className="mx-auto bg-pink-700 text-gray-300 hover:bg-pink-950 text-lg" type="button">
              Conheça a 42 São Paulo
            </Button>
          </Link>
        </div>
      </footer>
    </div>
  )
}