/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YS6prOEJWLF
 */

import React from 'react'

import { Button } from "../components/ui/button"

export default function v0() {
  return (
    <div className="flex flex-col min-h-screen bg-gray-900 text-gray-300">
      <nav className="bg-slate-800 p-4">
        <header className="mx-auto flex items-center justify-between">
          <a href="#">
            <div>
              <h1 className="text-xl font-semibold">ft_lanches | Nutrindo mentes</h1>
            </div>
          </a>
          <div className="flex space-x-4">
            <Button className="text-2xl bg-pink-600 text-gray-300 hover:bg-pink-950" type="button">
              doar
            </Button>
            <Button className="text-xl bg-blue-900 text-gray-300 hover:bg-blue-950" variant="secondary">
              login
            </Button>
          </div>
        </header>
      </nav>
      <main className="flex-grow mx-auto max-w-6xl flex-col justify-center">
        <img
          alt="ft_lanches"
          className="w-full"
          height={400}
          src="/ft_lanches.jpg"
          style={{
            aspectRatio: "800/400",
            objectFit: "cover",
          }}
          width={800}
        />
        <div className="relative">
          {/* <img
            alt="background"
            className="w-full h-full"
            height={400}
            src="/stars.jpg"
            style={{
              aspectRatio: "1000/400",
              objectFit: "cover",
            }}
            width={800}
          /> */}
          <div className="p-4 h-full flex flex-col justify-center items-center text-center space-y-4 bg-black bg-opacity-50">
            <p className="lg:text-5xl md:text-4xl sm:text-2xl text-slate-300">
              Ajude-nos a garantir que todos os cadetes da 42SP possam se alimentar adequadamente!
            </p>
            <p className="lg:text-4xl md:text-3xl sm:text-base text-slate-300">
              A 42 São Paulo é uma escola de engenharia de software gratuita e presencial, comprometida em promover
              diversidade no cenário tecnológico. No entanto, identificamos que alguns cadetes enfrentam dificuldades
              financeiras para fazer todas as refeições necessárias durante o dia no campus. Para solucionar esse
              problema, um grupo de cadetes decidiu agir!
            </p>
            <p className="lg:text-4xl md:text-3xl sm:text-base text-slate-300">
              A Carol (@anacaro3) estabeleceu uma parceria com um restaurante próximo à 42SP onde os participantes do
              programa ft_lanches poderão desfrutar das refeições oferecidas. E é aqui que você entra! Ao apoiar nosso
              projeto, você contribuirá para garantir que todos os cadetes tenham acesso às suas refeições diárias.
            </p>
            <p className="lg:text-4xl md:text-3xl sm:text-base text-slate-300">
              Com sua ajuda, poderemos atender a quantidade necessária de alunos e fornecer transparência total sobre
              como os fundos arrecadados são utilizados.
            </p>
            <p className="lg:text-4xl md:text-3xl sm:text-base text-slate-300">
              Venha fazer parte dessa campanha e faça a diferença na vida dos nossos cadetes! Juntos podemos fortalecer
              essa comunidade estudantil incrível!
            </p>
            <p className="lg:text-5xl md:text-4xl sm:text-3xl text-slate-300">
              Alimente o conhecimento - Apoie nossos Cadetes!
            </p>
            <p className="mb-2 text-center lg:text-5xl md:text-4xl sm:text-3xl text-slate-300">
              São 3 opções de assinatura:
            </p>
            <div className="grid grid-cols-3 gap-4 p-4">
              <Button className="mx-auto flex 4xl bg-pink-600 text-gray-300 hover:bg-pink-950" type="button">
                R$30/mês
              </Button>
              <Button className="mx-auto flex 4xl bg-pink-600 text-gray-300 hover:bg-pink-950" type="button">
                R$90/mês
              </Button>
              <Button className="mx-auto flex 4xl bg-pink-600 text-gray-300 hover:bg-pink-950" type="button">
                R$150/mês
              </Button>
            </div>
          </div>
        </div>
        <img
          alt="ft_lanche"
          className="w-full"
          height={400}
          src="/plate.jpg"
          style={{
            aspectRatio: "450/400",
            objectFit: "cover",
          }}
          width={800}
        />
      </main>
      <footer className="bg-gray-800 p-4">
        <div className="container mx-auto text-center">
          <Button className="mx-auto bg-gray-800 text-gray-300" type="button">
            Conheça a 42 São Paulo
          </Button>
        </div>
      </footer>
    </div>
  )
}
